apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubebuild.fullname" . }}
  labels:
    chart: {{ template "kubebuild.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config: |
    {{- if .Values.useReleaseAsInstanceID }}
    instanceID: {{ .Release.Name }}
    {{- else }}
    instanceID: {{ .Values.instanceID }}
    namespace: {{ .Release.Namespace }}
    {{- end }}
    artifactRepository:
      {{- if .Values.useDefaultArtifactRepo }}
      s3:
        {{- if .Values.useStaticCredentials }}
        accessKeySecret:
          key: accesskey
          name: kubebuild-s3
        secretKeySecret:
          key: secretkey
          name: kubebuild-s3
        {{- end }}
        bucket: {{ .Values.artifactRepository.s3.bucket }}
        keyPrefix: {{ .Values.artifactRepository.s3.keyPrefix }}
        endpoint: {{ .Values.artifactRepository.s3.endpoint }}
        insecure: {{ .Values.artifactRepository.s3.insecure }}
        region: {{ .Values.artifactRepository.s3.region }}
      {{- end}}
    executorImage: "{{ .Values.executorImage.repository }}:{{ .Values.executorImage.tag }}"
