apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubebuild.fullname" . }}-launcher
  labels:
    chart: {{ template "kubebuild.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}